### PR TITLE
changed test func to SmokeTest and light dox

### PR DESCRIPTION
**Pull request by tbenade**
Apologies on changing the interface but given the typo it was inevitable. I am taking liberties and suggesting a name change from Test to SmokeTest feels more explicit and mirrors the original implementation and adds possibility for other types of test functions.....but no idea what those would be.

### CODE REVIEW

**Comment by bernos** [comment]
All good but maybe just as an explanation of the behavior of the snookered callback. For example if you smoke test fails then call the callback with some value for the err argument to cause the deployment to halt

**Comment by bernos** [comment]
Bahaha "snookered" should be read as "smoke test"

**Comment by tbenade** [comment]
sorry my readme preview lied hold off on this till next commit please

**Comment by tbenade** [comment]
ok, sorry about that, tabs spaces tabs spaces....seriously just indent my list. Hows the doco, any better?

**Pull request merged**
